# Generated by Django 6.0.2 on 2026-07-17 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sla_days', models.SmallIntegerField(default=7)),
                ('status', models.CharField(default='ENABLED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_department_id', models.ForeignKey(db_column='service_department_id', on_delete=django.db.models.deletion.RESTRICT, to='departments.servicedepartment')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='ServiceDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=150)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_id', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'db_table': 'service_document',
            },
        ),
        migrations.CreateModel(
            name='ServiceField',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field_label', models.CharField(max_length=150)),
                ('field_type', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('display_order', models.SmallIntegerField(default=0)),
                ('options_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_id', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'db_table': 'service_field',
            },
        ),
    ]
