# Generated by Django 5.1.15 on 2026-09-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='service',
                    name='status',
                    field=models.BooleanField(default=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE service ALTER COLUMN status DROP DEFAULT; "
                        "ALTER TABLE service ALTER COLUMN status TYPE boolean "
                        "USING (CASE WHEN UPPER(status::text) IN ('ENABLED', 'ACTIVE', 'TRUE', '1', 'T') THEN TRUE ELSE FALSE END); "
                        "ALTER TABLE service ALTER COLUMN status SET DEFAULT TRUE;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE service ALTER COLUMN status DROP DEFAULT; "
                        "ALTER TABLE service ALTER COLUMN status TYPE varchar(10) "
                        "USING (CASE WHEN status IS TRUE THEN 'ENABLED' ELSE 'DISABLED' END); "
                        "ALTER TABLE service ALTER COLUMN status SET DEFAULT 'ENABLED';"
                    ),
                ),
            ],
        ),
    ]
