# Generated by Django 6.0.7 on 2026-08-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefield',
            name='conditional_logic',
            field=models.JSONField(blank=True, help_text='Controls when this field is visible.', null=True),
        ),
    ]
