# Generated by Django 6.0.2 on 2026-07-17 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_department_id',
            field=models.ForeignKey(blank=True, db_column='academic_department_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='departments.academicdepartment'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.RESTRICT, to='common.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='service_department_id',
            field=models.ForeignKey(blank=True, db_column='service_department_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='departments.servicedepartment'),
        ),
    ]
