# Generated by Django 6.0.7 on 2026-07-14 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('hod_user_id', models.ForeignKey(blank=True, db_column='hod_user_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='common.user')),
            ],
            options={
                'db_table': 'academicdepartment',
            },
        ),
        migrations.CreateModel(
            name='ServiceDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('hod_user_id', models.ForeignKey(blank=True, db_column='hod_user_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='common.user')),
            ],
            options={
                'db_table': 'servicedepartment',
            },
        ),
    ]
