# Generated by Django 6.0.2 on 2026-07-18 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDepartment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('degree', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=2)),
                ('category', models.CharField(max_length=10)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hod_user_id', models.ForeignKey(blank=True, db_column='hod_user_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='accounts.user')),
            ],
            options={
                'db_table': 'academic_department',
            },
        ),
        migrations.CreateModel(
            name='ServiceDepartment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hod_user_id', models.ForeignKey(blank=True, db_column='hod_user_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='accounts.user')),
            ],
            options={
                'db_table': 'service_department',
            },
        ),
    ]
