# Generated by Django 6.0.7 on 2026-07-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdepartment',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='academicdepartment',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
