# Generated by Django 6.0.7 on 2026-07-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicdepartment',
            name='branch',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicdepartment',
            name='category',
            field=models.CharField(choices=[('Arts', 'Arts'), ('Science', 'Science')], default='Science', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicdepartment',
            name='degree',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicdepartment',
            name='type',
            field=models.CharField(choices=[('UG', 'UG'), ('PG', 'PG')], default='UG', max_length=2),
            preserve_default=False,
        ),
    ]
