# Generated by Django 5.1.15 on 2026-08-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicdepartment',
            name='name',
        ),
        migrations.AddField(
            model_name='academicdepartment',
            name='stream',
            field=models.CharField(choices=[('SFM', 'SFM'), ('SFW', 'SFW'), ('Aided', 'Aided')], default='SFM', max_length=10),
        ),
    ]
