# Generated by Django 6.0.7 on 2026-09-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_academicdepartment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdepartment',
            name='category',
            field=models.CharField(choices=[('ARTS', 'Arts'), ('SCIENCE', 'Science')], max_length=100),
        ),
        migrations.AlterField(
            model_name='academicdepartment',
            name='type',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=100),
        ),
    ]
