# Generated by Django 5.1.15 on 2026-08-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_remove_academicdepartment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdepartment',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='academicdepartment',
            unique_together={('code', 'stream')},
        ),
    ]
