# Generated by Django 5.1.15 on 2026-08-04 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_academicdepartment_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicdepartment',
            name='hod_user_id',
        ),
    ]
