# Generated by Django 6.0.7 on 2026-09-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_alter_academicdepartment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicdepartment',
            options={'ordering': ['code', 'stream']},
        ),
    ]
