# Generated by Django 6.0.7 on 2026-08-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_remove_academicdepartment_hod_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedepartment',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
