# Generated by Django 6.0.7 on 2026-09-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_alter_academicdepartment_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='academicdepartment',
            index=models.Index(fields=['type', 'category'], name='academic_de_type_0df5b9_idx'),
        ),
    ]
