# Generated by Django 6.0.7 on 2026-07-14 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(max_length=30, unique=True)),
                ('batch_year', models.CharField(max_length=9)),
                ('mobile_number', models.CharField(max_length=15)),
                ('id_card_barcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('academic_department_id', models.ForeignKey(db_column='academic_department_id', on_delete=django.db.models.deletion.RESTRICT, to='departments.academicdepartment')),
                ('user_id', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.RESTRICT, to='common.user')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
