# Generated by Django 6.0.2 on 2026-07-17 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('register_number', models.CharField(max_length=30, unique=True)),
                ('batch_year', models.CharField(max_length=9)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('stream', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=15)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('aadhar_no', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('door_no', models.CharField(blank=True, max_length=20, null=True)),
                ('area_name', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=150, null=True)),
                ('parent_number', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_department_id', models.ForeignKey(db_column='academic_department_id', on_delete=django.db.models.deletion.RESTRICT, to='departments.academicdepartment')),
                ('user_id', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.RESTRICT, to='common.user')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
