# Generated by Django 6.0.7 on 2026-08-09 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('register_number', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('year_of_admission', models.CharField(max_length=9)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('stream', models.CharField(choices=[('SFM', 'SFM'), ('SFW', 'SFW'), ('AIDED', 'Aided')], default='SFM', max_length=10)),
                ('mobile_number', models.CharField(max_length=15)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_department_id', models.ForeignKey(db_column='academic_department_id', on_delete=django.db.models.deletion.RESTRICT, to='departments.academicdepartment')),
                ('user_id', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
