# Generated by Django 6.0.7 on 2026-08-06 19:34

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_aadhar_no_student_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadhar_no_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='aadhar_no',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=12, null=True)),
        ),
    ]
