# Generated by Django 6.0.7 on 2026-08-06 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_alter_servicedepartment_status'),
        ('students', '0004_student_aadhar_no_hash_alter_student_aadhar_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_department_id',
            field=models.ForeignKey(blank=True, db_column='academic_department_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='departments.academicdepartment'),
        ),
    ]
