# Generated by Django 6.0.7 on 2026-08-07 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_academic_department_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='allow_calls',
        ),
        migrations.RemoveField(
            model_name='student',
            name='allow_email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='allow_sms',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='preferred_contact_method',
        ),
    ]
