# Generated by Django 6.0.2 on 2026-07-17 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('requests', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='request_id',
            field=models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, to='requests.request'),
        ),
        migrations.AddField(
            model_name='document',
            name='service_document_id',
            field=models.ForeignKey(db_column='service_document_id', on_delete=django.db.models.deletion.RESTRICT, to='services.servicedocument'),
        ),
    ]
