# Generated by Django 6.0.7 on 2026-10-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='rejection_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
