from __future__ import annotations
from typing import Any

try:
    from apps.departments.models import AcademicDepartment
    HAS_MODEL = True
except Exception as exc:
    AcademicDepartment = None
    HAS_MODEL = False
    print(f"AcademicDepartment model could not be imported: {exc}")


def run() -> dict[str, Any]:
    """Seed the academic department table with official master data (71 records)."""

    if not HAS_MODEL:
        return {"created": 0, "updated": 0, "existing": 0, "skipped": True}

    print("\nSeeding academic departments with official master data...\n")

    departments = [   {   'branch': 'COMPUTER APPLICATIONS',
        'category': 'SCIENCE',
        'code': 'MCA',
        'degree': 'M.C.A.',
        'status': 'ACTIVE',
        'stream': 'Aided',
        'type': 'PG'},
    {   'branch': 'ARABIC',
        'category': 'ARTS',
        'code': 'PAR',
        'degree': 'M.A.',
        'status': 'ACTIVE',
        'stream': 'Aided',
        'type': 'PG'},
    {   'branch': 'BOTANY',
        'category': 'SCIENCE',
        'code': 'PBO',
        'degree': 'M.Sc.',
        'status': 'ACTIVE',
        'stream': 'Aided',
        'type': 'PG'},
    {   'branch': 'CHEMISTRY',
        'category': 'SCIENCE',
        'code': 'PCH',
        'degree': 'M.Sc.',
        'status': 'ACTIVE',
        'stream': 'Aided',
        'type': 'PG'},
    {   'branch': 'COMMERCE',
        'category': 'ARTS',
        'code': 'PCO',
        'degree': 'M.Com.',
        'status': 'ACTIVE',
        'stream': 'Aided',
        'type': 'PG'},
    {   'branch': 'ECONOMICS',
        'category': 'ARTS',
        'code': 'PEC',
        'degree': 'M.A.',
        'status': 'ACTIVE',
        'stream': 'Aided',
        'type': 'PG'},
    {   'branch': 'ENGLISH',
        'category': 'ARTS',
        'code': 'PEN',
        'degree': 'M.A.',
        'status': 'ACTIVE',
        'stream': 'Aided',
        'type': 'PG'},
    {   'branch': 'MATHEMATICS',
        'category': 'SCIENCE',
        'code': 'PMA',
        'degree': 'M.Sc.',
        'status': 'ACTIVE',
        'stream': 'Aided',
        'type': 'PG'},
    {   'branch': 'PHYSICS',
        'category': 'SCIENCE',
        'code': 'PPH',
        'degree': 'M.Sc.',
        'status': 'ACTIVE',
        'stream': 'Aided',
        'type': 'PG'},
    {   'branch': 'TAMIL',
        'category': 'ARTS',
        'code': 'PTA',
        'degree': 'M.A.',
        'status': 'ACTIVE',
        'stream': 'Aided',
        'type': 'PG'},
    {   'branch': 'ZOOLOGY',
        'category': 'SCIENCE',
        'code': 'PZO',
        'degree': 'M.Sc.',
        'status': 'ACTIVE',
        'stream': 'Aided',
        'type': 'PG'},
    {   'branch': 'ARABIC',
        'category': 'ARTS',
        'code': 'UAR',
        'degree': 'B.A.',
        'status': 'ACTIVE',
        'stream': 'Aided',
        'type': 'UG'},
    {   'branch': 'BOTANY',
        'category': 'SCIENCE',
        'code': 'UBO',
        'degree': 'B.Sc.',
        'status': 'ACTIVE',
        'stream': 'Aided',
        'type': 'UG'},
    {   'branch': 'CHEMISTRY',
        'category': 'SCIENCE',
        'code': 'UCH',
        'degree': 'B.Sc.',
        'status': 'ACTIVE',
        'stream': 'Aided',
        'type': 'UG'},
    {   'branch': 'COMMERCE',
        'category': 'ARTS',
        'code': 'UCO',
        'degree': 'B.Com.',
        'status': 'ACTIVE',
        'stream': 'Aided',
        'type': 'UG'},
    {   'branch': 'COMPUTER SCIENCE',
        'category': 'SCIENCE',
        'code': 'UCS',
        'degree': 'B.Sc.',
        'status': 'ACTIVE',
        'stream': 'Aided',
        'type': 'UG'},
    {   'branch': 'ECONOMICS',
        'category': 'ARTS',
        'code': 'UEC',
        'degree': 'B.A.',
        'status': 'ACTIVE',
        'stream': 'Aided',
        'type': 'UG'},
    {   'branch': 'ENGLISH',
        'category': 'ARTS',
        'code': 'UEN',
        'degree': 'B.A.',
        'status': 'ACTIVE',
        'stream': 'Aided',
        'type': 'UG'},
    {   'branch': 'HISTORY',
        'category': 'ARTS',
        'code': 'UHS',
        'degree': 'B.A.',
        'status': 'ACTIVE',
        'stream': 'Aided',
        'type': 'UG'},
    {   'branch': 'MATHEMATICS',
        'category': 'SCIENCE',
        'code': 'UMA',
        'degree': 'B.Sc.',
        'status': 'ACTIVE',
        'stream': 'Aided',
        'type': 'UG'},
    {   'branch': 'PHYSICS',
        'category': 'SCIENCE',
        'code': 'UPH',
        'degree': 'B.Sc.',
        'status': 'ACTIVE',
        'stream': 'Aided',
        'type': 'UG'},
    {   'branch': 'ZOOLOGY',
        'category': 'SCIENCE',
        'code': 'UZO',
        'degree': 'B.Sc.',
        'status': 'ACTIVE',
        'stream': 'Aided',
        'type': 'UG'},
    {   'branch': 'BUSINESS ADMINISTRATION',
        'category': 'ARTS',
        'code': 'MBA',
        'degree': 'M.B.A.',
        'status': 'ACTIVE',
        'stream': 'SFM',
        'type': 'PG'},
    {   'branch': 'COMPUTER APPLICATIONS',
        'category': 'SCIENCE',
        'code': 'MCA',
        'degree': 'M.C.A.',
        'status': 'ACTIVE',
        'stream': 'SFM',
        'type': 'PG'},
    {   'branch': 'SOCIAL WORK',
        'category': 'SCIENCE',
        'code': 'MSW',
        'degree': 'M.S.W.',
        'status': 'ACTIVE',
        'stream': 'SFM',
        'type': 'PG'},
    {   'branch': 'CHEMISTRY',
        'category': 'SCIENCE',
        'code': 'PCH',
        'degree': 'M.Sc.',
        'status': 'ACTIVE',
        'stream': 'SFM',
        'type': 'PG'},
    {   'branch': 'COMMERCE',
        'category': 'ARTS',
        'code': 'PCO',
        'degree': 'M.Com.',
        'status': 'ACTIVE',
        'stream': 'SFM',
        'type': 'PG'},
    {   'branch': 'COMPUTER SCIENCE',
        'category': 'SCIENCE',
        'code': 'PCS',
        'degree': 'M.Sc.',
        'status': 'ACTIVE',
        'stream': 'SFM',
        'type': 'PG'},
    {   'branch': 'HISTORY',
        'category': 'ARTS',
        'code': 'PHS',
        'degree': 'M.A.',
        'status': 'ACTIVE',
        'stream': 'SFM',
        'type': 'PG'},
    {   'branch': 'ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING',
        'category': 'SCIENCE',
        'code': 'UAI',
        'degree': 'B.Sc.',
        'status': 'ACTIVE',
        'stream': 'SFM',
        'type': 'UG'},
    {   'branch': 'AVIATION MANAGEMENT',
        'category': 'ARTS',
        'code': 'UAM',
        'degree': 'B.B.A.',
        'status': 'ACTIVE',
        'stream': 'SFM',
        'type': 'UG'},
    {   'branch': 'BUSINESS ADMINISTRATION',
        'category': 'ARTS',
        'code': 'UBA',
        'degree': 'B.B.A.',
        'status': 'ACTIVE',
        'stream': 'SFM',
        'type': 'UG'},
    {   'branch': 'COMPUTER APPLICATIONS',
        'category': 'SCIENCE',
        'code': 'UCA',
        'degree': 'B.C.A.',
        'status': 'ACTIVE',
        'stream': 'SFM',
        'type': 'UG'},
    {   'branch': 'COMMERCE',
        'category': 'ARTS',
        'code': 'UCO',
        'degree': 'B.Com.',
        'status': 'ACTIVE',
        'stream': 'SFM',
        'type': 'UG'},
    {   'branch': 'COMPUTER SCIENCE',
        'category': 'SCIENCE',
        'code': 'UCS',
        'degree': 'B.Sc.',
        'status': 'ACTIVE',
        'stream': 'SFM',
        'type': 'UG'},
    {   'branch': 'ENGLISH',
        'category': 'ARTS',
        'code': 'UEN',
        'degree': 'B.A.',
        'status': 'ACTIVE',
        'stream': 'SFM',
        'type': 'UG'},
    {   'branch': 'HOTEL MANAGEMENT AND CATERING SCIENCE',
        'category': 'SCIENCE',
        'code': 'UHM',
        'degree': 'B.Sc.',
        'status': 'ACTIVE',
        'stream': 'SFM',
        'type': 'UG'},
    {   'branch': 'INFORMATION TECHNOLOGY WITH CYBER SECURITY',
        'category': 'SCIENCE',
        'code': 'UIC',
        'degree': 'B.Sc.',
        'status': 'ACTIVE',
        'stream': 'SFM',
        'type': 'UG'},
    {   'branch': 'INTERNATIONAL FINANCE',
        'category': 'ARTS',
        'code': 'UIF',
        'degree': 'B.Com.',
        'status': 'ACTIVE',
        'stream': 'SFM',
        'type': 'UG'},
    {   'branch': 'TAMIL LITERATURE',
        'category': 'ARTS',
        'code': 'UTA',
        'degree': 'B.A.',
        'status': 'ACTIVE',
        'stream': 'SFM',
        'type': 'UG'},
    {   'branch': 'VISUAL COMMUNICATION',
        'category': 'SCIENCE',
        'code': 'UVC',
        'degree': 'B.Sc.',
        'status': 'ACTIVE',
        'stream': 'SFM',
        'type': 'UG'},
    {   'branch': 'BUSINESS ADMINISTRATION',
        'category': 'ARTS',
        'code': 'MBA',
        'degree': 'M.B.A.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'PG'},
    {   'branch': 'COMPUTER APPLICATIONS',
        'category': 'SCIENCE',
        'code': 'MCA',
        'degree': 'M.C.A.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'PG'},
    {   'branch': 'ARABIC',
        'category': 'ARTS',
        'code': 'PAR',
        'degree': 'M.A.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'PG'},
    {   'branch': 'BIOTECHNOLOGY',
        'category': 'SCIENCE',
        'code': 'PBT',
        'degree': 'M.Sc.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'PG'},
    {   'branch': 'CHEMISTRY',
        'category': 'SCIENCE',
        'code': 'PCH',
        'degree': 'M.Sc.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'PG'},
    {   'branch': 'COMMERCE',
        'category': 'ARTS',
        'code': 'PCO',
        'degree': 'M.Com.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'PG'},
    {   'branch': 'COMPUTER SCIENCE',
        'category': 'SCIENCE',
        'code': 'PCS',
        'degree': 'M.Sc.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'PG'},
    {   'branch': 'ENGLISH',
        'category': 'ARTS',
        'code': 'PEN',
        'degree': 'M.A.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'PG'},
    {   'branch': 'FASHION TECHNOLOGY AND COSTUME DESIGNING',
        'category': 'SCIENCE',
        'code': 'PFT',
        'degree': 'M.Sc.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'PG'},
    {   'branch': 'MATHEMATICS',
        'category': 'SCIENCE',
        'code': 'PMA',
        'degree': 'M.Sc.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'PG'},
    {   'branch': 'MICROBIOLOGY',
        'category': 'SCIENCE',
        'code': 'PMB',
        'degree': 'M.Sc.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'PG'},
    {   'branch': 'NUTRITION AND DIETETICS',
        'category': 'SCIENCE',
        'code': 'PND',
        'degree': 'M.Sc.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'PG'},
    {   'branch': 'ARABIC',
        'category': 'ARTS',
        'code': 'UAR',
        'degree': 'B.A.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'UG'},
    {   'branch': 'BUSINESS ADMINISTRATION',
        'category': 'ARTS',
        'code': 'UBA',
        'degree': 'B.B.A.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'UG'},
    {   'branch': 'BIOTECHNOLOGY',
        'category': 'SCIENCE',
        'code': 'UBT',
        'degree': 'B.Sc.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'UG'},
    {   'branch': 'COMPUTER APPLICATIONS',
        'category': 'SCIENCE',
        'code': 'UCA',
        'degree': 'B.C.A.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'UG'},
    {   'branch': 'COMMERCE WITH COMPUTER APPLICATIONS',
        'category': 'ARTS',
        'code': 'UCC',
        'degree': 'B.Com.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'UG'},
    {   'branch': 'CHEMISTRY',
        'category': 'SCIENCE',
        'code': 'UCH',
        'degree': 'B.Sc.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'UG'},
    {   'branch': 'COMMERCE',
        'category': 'ARTS',
        'code': 'UCO',
        'degree': 'B.Com.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'UG'},
    {   'branch': 'COMPUTER SCIENCE',
        'category': 'SCIENCE',
        'code': 'UCS',
        'degree': 'B.Sc.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'UG'},
    {   'branch': 'DATA SCIENCE',
        'category': 'SCIENCE',
        'code': 'UDS',
        'degree': 'B.Sc.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'UG'},
    {   'branch': 'ENGLISH',
        'category': 'ARTS',
        'code': 'UEN',
        'degree': 'B.A.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'UG'},
    {   'branch': 'FASHION TECHNOLOGY AND COSTUME DESIGNING',
        'category': 'SCIENCE',
        'code': 'UFT',
        'degree': 'B.Sc.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'UG'},
    {   'branch': 'INTERNATIONAL FINANCE',
        'category': 'ARTS',
        'code': 'UIF',
        'degree': 'B.Com.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'UG'},
    {   'branch': 'MATHEMATICS',
        'category': 'SCIENCE',
        'code': 'UMA',
        'degree': 'B.Sc.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'UG'},
    {   'branch': 'MICROBIOLOGY',
        'category': 'SCIENCE',
        'code': 'UMB',
        'degree': 'B.Sc.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'UG'},
    {   'branch': 'NUTRITION AND DIETETICS',
        'category': 'SCIENCE',
        'code': 'UND',
        'degree': 'B.Sc.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'UG'},
    {   'branch': 'PHYSICS',
        'category': 'SCIENCE',
        'code': 'UPH',
        'degree': 'B.Sc.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'UG'},
    {   'branch': 'TAMIL LITERATURE',
        'category': 'ARTS',
        'code': 'UTA',
        'degree': 'B.A.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'UG'},
    {   'branch': 'ZOOLOGY',
        'category': 'SCIENCE',
        'code': 'UZO',
        'degree': 'B.Sc.',
        'status': 'ACTIVE',
        'stream': 'SFW',
        'type': 'UG'}]

    created = 0
    updated = 0

    for department_data in departments:
        department, is_created = AcademicDepartment.objects.update_or_create(
            code=department_data["code"],
            stream=department_data["stream"],
            defaults={
                "degree": department_data["degree"],
                "branch": department_data["branch"],
                "type": department_data["type"],
                "category": department_data["category"],
                "status": department_data["status"],
            },
        )

        if is_created:
            created += 1
            print(f"Created department: {department.code} ({department.stream}) - {department.degree} {department.branch}")
        else:
            updated += 1
            print(f"Updated/Verified department: {department.code} ({department.stream}) - {department.degree} {department.branch}")

    print(
        f"Academic department seeding completed. "
        f"Created: {created}, Updated/Verified: {updated}, Total: {len(departments)}"
    )

    return {
        "created": created,
        "updated": updated,
        "total": len(departments),
        "skipped": False,
    }
