# Generated by Django 6.0.2 on 2026-07-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gateway_txn_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_status', models.CharField(default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
