# Generated by Django 6.0.7 on 2026-07-14 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='request_id',
            field=models.OneToOneField(db_column='request_id', on_delete=django.db.models.deletion.RESTRICT, to='requests.request'),
        ),
    ]
