# Generated by Django 6.0.2 on 2026-07-18 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
        ('services', '__first__'),
        ('students', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='current_step_id',
            field=models.ForeignKey(blank=True, db_column='current_step_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='workflow.workflowstep'),
        ),
        migrations.AddField(
            model_name='request',
            name='service_id',
            field=models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.RESTRICT, to='services.service'),
        ),
        migrations.AddField(
            model_name='request',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.RESTRICT, to='students.student'),
        ),
        migrations.AddField(
            model_name='requestfieldvalue',
            name='field_id',
            field=models.ForeignKey(db_column='field_id', on_delete=django.db.models.deletion.RESTRICT, to='services.servicefield'),
        ),
        migrations.AddField(
            model_name='requestfieldvalue',
            name='request_id',
            field=models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, to='requests.request'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['student_id', 'current_status'], name='request_student_8b10fe_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['service_id', 'current_status'], name='request_service_8e74c9_idx'),
        ),
    ]
