# Generated by Django 6.0.7 on 2026-07-20 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('requests', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('step_order', models.SmallIntegerField()),
                ('step_name', models.CharField(max_length=150)),
                ('action_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible_role_id', models.ForeignKey(db_column='responsible_role_id', on_delete=django.db.models.deletion.RESTRICT, to='common.role')),
                ('responsible_role_id', models.ForeignKey(db_column='responsible_role_id', on_delete=django.db.models.deletion.RESTRICT, to='accounts.role')),
                ('service_id', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'db_table': 'workflow_step',
                'unique_together': {('service_id', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('action_by_user_id', models.ForeignKey(db_column='action_by_user_id', on_delete=django.db.models.deletion.RESTRICT, to='accounts.user')),
                ('request_id', models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, to='requests.request')),
                ('step_id', models.ForeignKey(blank=True, db_column='step_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='workflow.workflowstep')),
            ],
            options={
                'db_table': 'workflow_history',
                'indexes': [models.Index(fields=['request_id', 'action_at'], name='workflow_hi_request_44400b_idx')],
            },
        ),
    ]
