# Generated by Django 6.0.7 on 2026-08-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowstep',
            options={'ordering': ['step_order', 'id']},
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='allowed_actions',
            field=models.JSONField(blank=True, default=list, help_text="List of allowed action codes for this step, e.g. ['APPROVE', 'REJECT', 'RETURN']"),
        ),
    ]
