# Generated by Django 6.0.7 on 2026-08-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('ACTIVATE', 'Activate'), ('DEACTIVATE', 'Deactivate'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('UPLOAD', 'Upload'), ('EXPORT', 'Export'), ('IMPORT', 'Import')], max_length=10),
        ),
    ]
