# Generated by Django 6.0.7 on 2026-09-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('ACTIVATE', 'Activate'), ('DEACTIVATE', 'Deactivate'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('UPLOAD', 'Upload'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILURE', 'Login Failure'), ('REFRESH', 'Token Refresh'), ('REUSE_DETECTED', 'Token Reuse Detected'), ('LOGOUT_ALL', 'Logout All Sessions'), ('VALIDATE_MISMATCH', 'Role/privilege Mismatch')], max_length=50),
        ),
    ]
