# Generated by Django 6.0.7 on 2026-08-09 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='request_id',
            field=models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, to='requests.request'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('event_code', 'channel')},
        ),
        migrations.AddField(
            model_name='notification',
            name='template_id',
            field=models.ForeignKey(db_column='template_id', on_delete=django.db.models.deletion.RESTRICT, to='notifications.notificationtemplate'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['request_id'], name='notificatio_request_a75858_idx'),
        ),
    ]
